### ISSUE TITLE
Add ESLint to improve code quality and consistency

### ISSUE THREAD

**Issue by RoshanPShetty** [RoshanPShetty/chromets-launchpad#1]
## Background
ESLint is a powerful tool for identifying and fixing problems in JavaScript code. Adding it to our boilerplate will help maintain code quality and consistency across the project.

## Objective
Integrate ESLint into the ChromeTS Launchpad boilerplate to enforce coding standards and catch potential errors early in the development process.

## Tasks
- [ ] Install necessary ESLint packages:
  ```
  npm install --save-dev eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
  ```
- [ ] Create an ESLint configuration file (`.eslintrc.js` or `.eslintrc.json`) in the project root.
- [ ] Configure ESLint for TypeScript (use `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin`).
- [ ] Add lint scripts to `package.json`:
  ```json
  "scripts": {
    "lint": "eslint . --ext .ts",
    "lint:fix": "eslint . --ext .ts --fix"
  }
  ```
- [ ] Create a `.eslintignore` file to exclude certain directories/files (e.g., `dist`, `node_modules`).
- [ ] Update the README.md with information about linting.
- [ ] (Optional) Integrate ESLint with the existing build process.

## Resources
- [ESLint Getting Started Guide](https://eslint.org/docs/user-guide/getting-started)
- [TypeScript ESLint](https://github.com/typescript-eslint/typescript-eslint)

## Notes
- Feel free to suggest or implement additional ESLint rules that you think would be beneficial for the project.
- If you have any questions or need clarification, please ask in the comments!

**Comment by himanshuraimau** [comment]
hey can i work on this.

**Comment by RoshanPShetty** [comment]
Assigned. If you have any questions or need clarification, please ask in the comments!

**Comment by himanshuraimau** [comment]
okay !

**Comment by himanshuraimau** [comment]
the work is done please check the pr.

**Comment by RoshanPShetty** [comment]
I had to tweak some minor things here and there but apart from that good job. Please double check before submitting a PR if the build works or not. I am closing this as I have merged your PR with my additional changes.

**Comment by himanshuraimau** [comment]
oh okay will check that from now!
