### ISSUE TITLE
Add Jest for unit testing TypeScript code

### ISSUE THREAD

**Issue by RoshanPShetty** [RoshanPShetty/chromets-launchpad#2]
## Background
Unit testing is a crucial part of maintaining code quality and preventing regressions. Adding Jest, a popular JavaScript testing framework, to our boilerplate will provide a solid foundation for writing and running tests.

## Objective
Integrate Jest into the ChromeTS Launchpad boilerplate to enable unit testing for TypeScript code.

## Tasks
- [ ] Install necessary packages:
  ```
  npm install --save-dev jest @types/jest ts-jest
  ```
- [ ] Create a Jest configuration file (`jest.config.js`) in the project root:
  ```javascript
  module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
    moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  };
  ```
- [ ] Add test scripts to `package.json`:
  ```json
  "scripts": {
    "test": "jest",
    "test:watch": "jest --watch"
  }
  ```
- [ ] Create a sample test file (e.g., `src/__tests__/sample.test.ts`) with a basic test:
  ```typescript
  describe('Sample Test', () => {
    it('should pass', () => {
      expect(true).toBe(true);
    });
  });
  ```
- [ ] Update the README.md with information about running tests.
- [ ] (Optional) Set up GitHub Actions to run tests automatically on push and pull requests.

## Resources
- [Jest Documentation](https://jestjs.io/docs/getting-started)
- [ts-jest](https://github.com/kulshekhar/ts-jest)

## Notes
- Feel free to add more sample tests or suggest improvements to the testing setup.
- If you have any questions or need clarification, please ask in the comments!

**Comment by himanshuraimau** [comment]
can i work on this?
